spring:
  datasource:
    password: crypto
    username: crypto
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: oracle
    database-platform: org.hibernate.dialect.Oracle10gDialect

server:
  port: 80